[package]
name = "moried"
version = "0.4.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-argon2 = "1.0.0"
bytes = "0.5.6"
chrono = { version = "0.4.12", features = ["serde"] }
dotenv = "0.15.0"
futures = "0.3"
git2 = "0.13"
jsonwebtoken = "7"
mime_guess = "2.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.13"
urlencoding = "1.1.1"
axum = { version = "0.5.10", features = ["multipart"] }
axum-macros = "0.2.3"
hyper = { version = "0.14.19", features = ["full"] }
tokio = { version = "1.19.2", features = ["full"] }
tower = { version = "0.4.13", features = ["buffer", "limit", "load-shed"] }
tower-http = { version = "0.3.4", features = ["compression-gzip", "cors", "sensitive-headers", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
