[package]
name = "moried"
version = "0.4.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-argon2 = "0.8.2"
bytes = "0.5.6"
chrono = { version = "0.4.12", features = ["serde"] }
dotenv = "0.15.0"
futures = "0.3"
git2 = "0.13"
jsonwebtoken = "7"
log = "0.4"
mime_guess = "2.0.3"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.13"
tokio = { version = "0.2", features = ["io-util", "macros"] }
urlencoding = "1.1.1"
warp = { version = "0.2", default-features = false, features = ["multipart", "compression"] }
