[package]
name = "moried"
version = "1.0.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-argon2 = "1.0.0"
bytes = "1.4.0"
chrono = { version = "0.4.12", features = ["serde"] }
dotenv = "0.15.0"
futures = "0.3"
git2 = { version = "0.16", default-features = false }
jsonwebtoken = "8"
mime_guess = "2.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.17"
urlencoding = "2.1.2"
axum = { version = "0.6.4", features = ["macros", "multipart"] }
axum-macros = "0.3.2"
hyper = { version = "0.14.19", features = ["full"] }
tokio = { version = "1.19.2", features = ["full"] }
tower = { version = "0.4.13", features = ["buffer", "limit", "load-shed"] }
tower-http = { version = "0.3.4", features = ["compression-gzip", "cors", "sensitive-headers", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
