[package]
name = "moried"
version = "0.1.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
git2 = "0.13"
log = "0.4"
mime_guess = "2.0.3"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.13"
tokio = { version = "0.2", features = ["io-util", "macros"] }
urlencoding = "1.1.1"
warp = "0.2"
